// Bibliothèque d'emojis avec mots-clés FRANÇAIS pour la recherche (post-it +
// tâches). Chaque entrée : `e` = emoji, `kw` = mots-clés (recherche insensible
// aux accents et à la casse, voir normalize côté composant). Liste volontairement
// large mais lisible ; on peut en ajouter au besoin.

export type EmojiEntry = { e: string; kw: string };
export type EmojiGroup = { label: string; items: EmojiEntry[] };

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    label: "Smileys & émotions",
    items: [
      { e: "😀", kw: "sourire content heureux visage rire joie" },
      { e: "😁", kw: "sourire dents content heureux joie" },
      { e: "😂", kw: "rire pleurer larmes mdr lol drole" },
      { e: "🤣", kw: "rire terre plie mort de rire lol drole" },
      { e: "😊", kw: "sourire timide content mignon heureux" },
      { e: "🙂", kw: "sourire leger content" },
      { e: "😍", kw: "amour yeux coeur adorer craquer" },
      { e: "🥰", kw: "amour coeurs adorable tendresse" },
      { e: "😘", kw: "bisou bise coeur amour" },
      { e: "😎", kw: "cool lunettes soleil classe stylé" },
      { e: "🤩", kw: "etoiles waouh impressionne admiration" },
      { e: "🥳", kw: "fete anniversaire cotillon celebration" },
      { e: "😉", kw: "clin oeil complice malin" },
      { e: "🤗", kw: "calin bras embrasser accueil" },
      { e: "🤔", kw: "reflexion penser doute hmm question" },
      { e: "🤨", kw: "sourcil doute suspicion perplexe" },
      { e: "😐", kw: "neutre sans expression blase" },
      { e: "😴", kw: "dormir fatigue sommeil zzz" },
      { e: "😪", kw: "fatigue endormi somnolent" },
      { e: "🤤", kw: "bave envie miam gourmand" },
      { e: "😭", kw: "pleurer triste larmes chagrin" },
      { e: "😢", kw: "triste larme pleurer chagrin" },
      { e: "😅", kw: "rire gene sueur soulagement ouf" },
      { e: "😬", kw: "grimace gene malaise crispé" },
      { e: "😳", kw: "gene choc rougir surpris" },
      { e: "🥺", kw: "supplier yeux tristes pitie mignon" },
      { e: "😡", kw: "colere enerve fache rouge rage" },
      { e: "😤", kw: "enerve vapeur frustre determine" },
      { e: "😱", kw: "peur cri choc panique effraye" },
      { e: "😨", kw: "peur inquiet angoisse" },
      { e: "😰", kw: "stress angoisse sueur inquiet" },
      { e: "🤯", kw: "explose tete choc waouh incroyable" },
      { e: "😵", kw: "etourdi ko sonne" },
      { e: "🤒", kw: "malade fievre thermometre" },
      { e: "🤕", kw: "blesse bandage bobo" },
      { e: "🤢", kw: "degout nausee vomir malade" },
      { e: "😷", kw: "masque malade maladie" },
      { e: "🤫", kw: "chut silence secret" },
      { e: "🤐", kw: "bouche cousue silence secret" },
      { e: "😏", kw: "sourire narquois malicieux" },
      { e: "🙄", kw: "yeux au ciel agace blase" },
      { e: "😌", kw: "soulage calme serein apaise" },
      { e: "🤓", kw: "intello lunettes nerd geek" },
      { e: "🥱", kw: "baille fatigue ennui" },
      { e: "👍", kw: "pouce bien ok daccord super valider" },
      { e: "👎", kw: "pouce bas non mauvais refuser" },
    ],
  },
  {
    label: "Gestes & mains",
    items: [
      { e: "👏", kw: "applaudir bravo felicitations mains" },
      { e: "🙌", kw: "mains levees youpi bravo victoire" },
      { e: "🙏", kw: "prier merci sil te plait espoir mains" },
      { e: "🤝", kw: "poignee main accord deal partenariat" },
      { e: "✌️", kw: "victoire paix deux doigts" },
      { e: "🤞", kw: "doigts croises chance espoir" },
      { e: "👌", kw: "ok parfait daccord" },
      { e: "🤙", kw: "appelle telephone cool shaka" },
      { e: "💪", kw: "muscle force fort motivation sport" },
      { e: "👀", kw: "yeux regarder voir attention" },
      { e: "👋", kw: "salut bonjour au revoir main" },
      { e: "✊", kw: "poing force solidarite" },
      { e: "👉", kw: "doigt pointer droite ici" },
      { e: "👇", kw: "doigt pointer bas dessous" },
      { e: "☝️", kw: "doigt haut un point important" },
      { e: "🫶", kw: "coeur mains amour merci" },
    ],
  },
  {
    label: "Cœurs & amour",
    items: [
      { e: "❤️", kw: "coeur rouge amour" },
      { e: "🧡", kw: "coeur orange amour" },
      { e: "💛", kw: "coeur jaune amour amitie" },
      { e: "💚", kw: "coeur vert amour nature" },
      { e: "💙", kw: "coeur bleu amour" },
      { e: "💜", kw: "coeur violet amour" },
      { e: "🖤", kw: "coeur noir" },
      { e: "🤍", kw: "coeur blanc" },
      { e: "💕", kw: "coeurs amour tendresse" },
      { e: "💖", kw: "coeur brillant amour etincelant" },
      { e: "💗", kw: "coeur grandissant amour" },
      { e: "💘", kw: "coeur fleche cupidon amour" },
      { e: "💯", kw: "cent parfait note top pur" },
      { e: "💔", kw: "coeur brise chagrin rupture" },
    ],
  },
  {
    label: "Symboles utiles",
    items: [
      { e: "📌", kw: "punaise epingle important fixer note" },
      { e: "📍", kw: "epingle lieu position localisation" },
      { e: "⭐", kw: "etoile favori important note top" },
      { e: "🌟", kw: "etoile brillante special magique" },
      { e: "✨", kw: "etincelles brillant magie nouveau propre" },
      { e: "🔥", kw: "feu chaud tendance top motivation urgent" },
      { e: "💡", kw: "idee ampoule lumiere inspiration" },
      { e: "✅", kw: "coche valide fait ok termine vert" },
      { e: "☑️", kw: "case cochee valide fait" },
      { e: "✔️", kw: "coche valide oui fait" },
      { e: "❌", kw: "croix erreur non faux annuler rouge" },
      { e: "⚠️", kw: "attention avertissement danger prudence" },
      { e: "❗", kw: "exclamation important attention" },
      { e: "❓", kw: "question interrogation doute" },
      { e: "‼️", kw: "double exclamation urgent important" },
      { e: "🚫", kw: "interdit non stop defense" },
      { e: "⛔", kw: "interdit sens interdit stop" },
      { e: "🎯", kw: "cible objectif but precision" },
      { e: "🏆", kw: "trophee gagnant victoire recompense" },
      { e: "🥇", kw: "medaille or premier gagnant" },
      { e: "🎖️", kw: "medaille honneur recompense" },
      { e: "🔔", kw: "cloche notification rappel alerte" },
      { e: "🔕", kw: "cloche barree silence muet" },
      { e: "🔒", kw: "cadenas ferme securite prive" },
      { e: "🔑", kw: "cle acces mot de passe" },
      { e: "♻️", kw: "recyclage recycler ecologie" },
      { e: "✳️", kw: "asterisque etoile special" },
      { e: "🆕", kw: "nouveau new" },
      { e: "🔴", kw: "rond rouge point urgent" },
      { e: "🟠", kw: "rond orange point" },
      { e: "🟡", kw: "rond jaune point" },
      { e: "🟢", kw: "rond vert point ok" },
      { e: "🔵", kw: "rond bleu point" },
      { e: "🟣", kw: "rond violet point" },
    ],
  },
  {
    label: "Travail & objets",
    items: [
      { e: "📝", kw: "note ecrire memo redaction crayon" },
      { e: "✏️", kw: "crayon ecrire noter dessiner" },
      { e: "🖊️", kw: "stylo ecrire signer" },
      { e: "📋", kw: "presse papier liste checklist taches" },
      { e: "📅", kw: "calendrier date rendez vous agenda" },
      { e: "📆", kw: "calendrier date jour echeance" },
      { e: "🗓️", kw: "calendrier planning agenda" },
      { e: "⏰", kw: "reveil heure alarme rappel temps" },
      { e: "⏳", kw: "sablier temps attente delai" },
      { e: "📁", kw: "dossier fichier ranger classer" },
      { e: "📂", kw: "dossier ouvert fichier" },
      { e: "📎", kw: "trombone piece jointe attacher" },
      { e: "📊", kw: "graphique barres statistiques donnees" },
      { e: "📈", kw: "graphique hausse croissance progression" },
      { e: "📉", kw: "graphique baisse chute perte" },
      { e: "💻", kw: "ordinateur portable travail informatique" },
      { e: "🖥️", kw: "ordinateur bureau ecran" },
      { e: "🖱️", kw: "souris ordinateur" },
      { e: "⌨️", kw: "clavier taper ordinateur" },
      { e: "📱", kw: "telephone portable mobile smartphone" },
      { e: "☎️", kw: "telephone appel appeler" },
      { e: "📞", kw: "telephone appel appeler combine" },
      { e: "📧", kw: "email mail courriel message" },
      { e: "✉️", kw: "enveloppe courrier lettre message" },
      { e: "📷", kw: "appareil photo camera image" },
      { e: "📸", kw: "photo flash appareil" },
      { e: "🎥", kw: "camera video film tournage" },
      { e: "🎬", kw: "clap cinema film video montage" },
      { e: "🎨", kw: "palette art peinture design dessin creatif" },
      { e: "🖌️", kw: "pinceau peindre design art" },
      { e: "🖍️", kw: "craie couleur dessin" },
      { e: "✒️", kw: "plume ecrire signature" },
      { e: "📖", kw: "livre lire lecture cours" },
      { e: "📚", kw: "livres etudes cours ecole bibliotheque" },
      { e: "🔖", kw: "marque page signet enregistrer" },
      { e: "💼", kw: "mallette travail business boulot" },
      { e: "🗂️", kw: "classeur dossiers organiser" },
      { e: "🗑️", kw: "poubelle supprimer jeter corbeille" },
      { e: "🔧", kw: "cle outil reparer reglage" },
      { e: "🔨", kw: "marteau bricoler construire" },
      { e: "⚙️", kw: "engrenage reglage parametre config" },
      { e: "🧩", kw: "puzzle piece solution" },
      { e: "💰", kw: "argent sac fric money finance" },
      { e: "💸", kw: "argent envole depense billet" },
      { e: "💵", kw: "billet argent dollars" },
      { e: "💳", kw: "carte bancaire paiement banque" },
      { e: "🧾", kw: "recu facture ticket note" },
      { e: "🏦", kw: "banque finance" },
    ],
  },
  {
    label: "Vie & santé",
    items: [
      { e: "🏠", kw: "maison domicile chez soi" },
      { e: "🛒", kw: "caddie courses achats panier" },
      { e: "🍔", kw: "burger manger nourriture fast food" },
      { e: "🍕", kw: "pizza manger nourriture" },
      { e: "🍎", kw: "pomme fruit manger sain" },
      { e: "🥗", kw: "salade sain manger legume" },
      { e: "☕", kw: "cafe boisson pause chaud" },
      { e: "🍺", kw: "biere boisson apero" },
      { e: "🍷", kw: "vin verre boisson apero" },
      { e: "💊", kw: "medicament pilule sante pharmacie" },
      { e: "🩺", kw: "stethoscope medecin sante docteur rdv" },
      { e: "🏃", kw: "courir sport course jogging" },
      { e: "🏋️", kw: "musculation sport salle fitness" },
      { e: "🧘", kw: "yoga meditation calme detente" },
      { e: "⚽", kw: "football foot ballon sport" },
      { e: "🏀", kw: "basket ballon sport" },
      { e: "🎾", kw: "tennis balle sport" },
      { e: "🚗", kw: "voiture conduire auto deplacement" },
      { e: "✈️", kw: "avion voyage vol vacances" },
      { e: "🚆", kw: "train transport voyage" },
      { e: "🚲", kw: "velo bicyclette sport deplacement" },
      { e: "🌍", kw: "terre monde global planete voyage" },
      { e: "🎁", kw: "cadeau present anniversaire offrir" },
      { e: "🎉", kw: "fete cotillon celebration bravo" },
      { e: "🎈", kw: "ballon fete anniversaire" },
    ],
  },
  {
    label: "Nature & météo",
    items: [
      { e: "☀️", kw: "soleil beau temps chaud jour" },
      { e: "🌤️", kw: "soleil nuage eclaircie" },
      { e: "☁️", kw: "nuage nuageux temps" },
      { e: "🌧️", kw: "pluie parapluie temps mauvais" },
      { e: "⛈️", kw: "orage eclair pluie tempete" },
      { e: "❄️", kw: "neige flocon froid hiver" },
      { e: "🌈", kw: "arc en ciel couleurs espoir" },
      { e: "🌙", kw: "lune nuit soir" },
      { e: "🌊", kw: "vague mer ocean eau" },
      { e: "🌸", kw: "fleur cerisier printemps rose" },
      { e: "🌹", kw: "rose fleur amour" },
      { e: "🌿", kw: "feuille plante nature vert" },
      { e: "🌱", kw: "pousse plante debut croissance nouveau" },
      { e: "🌳", kw: "arbre nature foret" },
      { e: "🍀", kw: "trefle chance porte bonheur" },
      { e: "🐶", kw: "chien animal chiot" },
      { e: "🐱", kw: "chat animal chaton" },
      { e: "🐾", kw: "pattes empreintes animal" },
      { e: "🦋", kw: "papillon insecte nature transformation" },
      { e: "🐝", kw: "abeille insecte miel travail" },
    ],
  },
];

// Liste à plat (pour la recherche globale).
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.items);

// Normalise pour une recherche insensible aux accents et à la casse.
export function normalizeSearch(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}
